# generated by datamodel-codegen:
#   filename:  common/envelope.schema.json
#   timestamp: 2026-07-17T11:02:36+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field


class EventEnvelope(BaseModel):
    """
    Common fields present on every event published to the bus. Each event schema merges this with its own `payload` shape via allOf.
    """

    event_id: UUID = Field(
        ..., description='Unique ID for this specific event instance (not the request).'
    )
    request_id: UUID = Field(
        ...,
        description='Correlation ID shared by every event belonging to the same patient request, from submission to closure. This is how Evaluation reconstructs a full request lifecycle across services.',
    )
    event_type: str = Field(
        ...,
        description="Redis Stream key / logical event name, e.g. 'request.submitted'.",
    )
    version: str = Field(
        ...,
        description="Schema version for this event type, e.g. '1.0'. Bump on breaking changes so consumers can branch on it during migration.",
    )
    produced_at: AwareDatetime = Field(
        ...,
        description='ISO 8601 UTC timestamp of when the producing service emitted this event.',
    )
    producer: str = Field(
        ...,
        description="Name of the service that published this event, e.g. 'ingestion', 'nlp-triage'. Useful for debugging and for Evaluation's traceability.",
    )
