# generated by datamodel-codegen:
#   filename:  pro.profile_updated.schema.json
#   timestamp: 2026-07-18T19:16:23+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .common.envelope_schema import EventEnvelope


class ProfileUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pro_id: str = Field(..., description="Professional's unique ID.")
    specialty: str = Field(
        ...,
        description="Declared specialty/profession, e.g. 'infirmier', 'médecin généraliste'.",
    )
    description: str = Field(
        ...,
        description='Free-text profile description used as the basis for the semantic embedding (this is what gets compared against request.case_embedded via cosine similarity).',
    )


class ProProfileUpdated(EventEnvelope):
    """
    Published by Pro Registry whenever a professional's profile changes (specialty, description, etc). IA3/matching_db keeps its embedding of the pro's profile in sync by re-embedding on this event.
    """

    event_type: Literal['pro.profile_updated'] = Field(
        ...,
        description="Redis Stream key / logical event name, e.g. 'request.submitted'.",
    )
    payload: ProfileUpdatedPayload = Field(..., title='ProfileUpdatedPayload')
