# generated by datamodel-codegen:
#   filename:  pro.availability_changed.schema.json
#   timestamp: 2026-07-17T11:02:36+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .common.envelope_schema import EventEnvelope


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pro_id: str = Field(..., description="Professional's unique ID.")
    available: bool = Field(
        ..., description='Whether the professional can currently receive new proposals.'
    )
    current_load: int | None = Field(
        None,
        description='Number of active cases currently assigned to this professional, if tracked. Used by Dispatch Core to avoid overloading a single pro.',
        ge=0,
    )


class ProAvailabilityChanged(EventEnvelope):
    """
    Published by Pro Registry whenever a professional's availability or current workload changes. Dispatch Core consumes this to keep its candidate pool current without needing to poll Pro Registry synchronously.
    """

    event_type: Literal['pro.availability_changed'] = Field(
        ...,
        description="Redis Stream key / logical event name, e.g. 'request.submitted'.",
    )
    payload: Payload
