# generated by datamodel-codegen:
#   filename:  request.submitted.schema.json
#   timestamp: 2026-07-18T19:16:23+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .common.envelope_schema import EventEnvelope


class SubmittedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    patient_id: str = Field(
        ...,
        description='Identifier for the patient submitting the request. In this prototype this is a synthetic/simulated ID (no real health data — out of scope per the doc).',
    )
    text: str = Field(
        ...,
        description="Raw free-text description of the patient's situation, exactly as submitted. This is the only input IA1 works from.",
        min_length=1,
    )


class RequestSubmitted(EventEnvelope):
    """
    Published by Ingestion the moment a patient's raw text request is received. This is the entry point of the whole pipeline — everything downstream (IA1, IA2, IA3, Dispatch Core) traces back to this event via request_id.
    """

    event_type: Literal['request.submitted'] = Field(
        ...,
        description="Redis Stream key / logical event name, e.g. 'request.submitted'.",
    )
    payload: SubmittedPayload = Field(..., title='SubmittedPayload')
