# generated by datamodel-codegen:
#   filename:  request.case_embedded.schema.json
#   timestamp: 2026-07-17T11:02:36+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .common.envelope_schema import EventEnvelope


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    embedding: list[float] = Field(
        ...,
        description="The embedding vector for this request's case. Length must match `dimension` and the pgvector column dimension in matching_db.",
        min_length=1,
    )
    dimension: int = Field(
        ...,
        description='Length of the embedding vector, e.g. 384 for all-MiniLM-L6-v2.',
        ge=1,
    )
    embedding_model: str = Field(
        ...,
        description="Identifier of the sentence-transformers model used, e.g. 'sentence-transformers/all-MiniLM-L6-v2'. Needed so Evaluation/Dispatch never compare vectors produced by two different models.",
    )


class RequestCaseEmbedded(EventEnvelope):
    """
    Published by IA3 (Matching) after computing a semantic embedding of the request. Dispatch Core uses this vector to find the professional with the highest cosine similarity via pgvector, for the semantic-matching strategies (S3/S4).
    """

    event_type: Literal['request.case_embedded'] = Field(
        ...,
        description="Redis Stream key / logical event name, e.g. 'request.submitted'.",
    )
    payload: Payload
