# generated by datamodel-codegen:
#   filename:  request.urgency_score.schema.json
#   timestamp: 2026-07-17T11:02:36+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .common.envelope_schema import EventEnvelope


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    score: int = Field(
        ...,
        description="0 = non-urgent, 3 = critical/emergency. Drives Dispatch Core's prioritization within the queue.",
        ge=0,
        le=3,
    )
    rationale: str | None = Field(
        None,
        description='Short human-readable explanation for the score, useful for debugging and for the Evaluation report.',
    )
    confidence: float = Field(
        ..., description="IA2's confidence in this score.", ge=0.0, le=1.0
    )


class RequestUrgencyScore(EventEnvelope):
    """
    Published by IA2 (Urgency Scoring) after scoring a request's urgency on a 0-3 scale. Dispatch Core waits for both this event and request.case_embedded before it can act on a request.
    """

    event_type: Literal['request.urgency_score'] = Field(
        ...,
        description="Redis Stream key / logical event name, e.g. 'request.submitted'.",
    )
    payload: Payload
