# generated by datamodel-codegen:
#   filename:  request.accepted.schema.json
#   timestamp: 2026-07-17T11:02:36+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .common.envelope_schema import EventEnvelope


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pro_id: str = Field(..., description='ID of the professional who accepted.')
    ttfa_seconds: float | None = Field(
        None,
        description='Time-to-first-assignment: seconds elapsed between request.submitted and this acceptance. One of the key KPIs Evaluation compares across strategies.',
        ge=0.0,
    )


class RequestAccepted(EventEnvelope):
    """
    Published by Dispatch Core when the proposed professional accepts the request (FSM transition: proposed -> accepted). This is generally followed by request.closed once the case wraps up.
    """

    event_type: Literal['request.accepted'] = Field(
        ...,
        description="Redis Stream key / logical event name, e.g. 'request.submitted'.",
    )
    payload: Payload
