# generated by datamodel-codegen:
#   filename:  request.closed.schema.json
#   timestamp: 2026-07-17T11:02:36+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .common.envelope_schema import EventEnvelope


class Outcome(Enum):
    """
    Terminal outcome of the request.
    """

    dispatched = 'dispatched'
    cancelled = 'cancelled'
    no_professional_available = 'no_professional_available'
    timeout = 'timeout'


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outcome: Outcome = Field(..., description='Terminal outcome of the request.')
    pro_id: str | None = Field(
        None,
        description="Professional ultimately assigned, if outcome is 'dispatched'; null otherwise.",
    )
    ttfa_seconds: float | None = Field(
        None,
        description='Final time-to-first-assignment for this request, for KPI aggregation.',
        ge=0.0,
    )
    total_refusals: int = Field(
        ...,
        description='Total number of professionals who refused/timed-out before closure.',
        ge=0,
    )


class RequestClosed(EventEnvelope):
    """
    Published by Dispatch Core when a request reaches a terminal FSM state, successful or not. This is the final event in a request's lifecycle and the one Evaluation waits for to compute per-request KPIs.
    """

    event_type: Literal['request.closed'] = Field(
        ...,
        description="Redis Stream key / logical event name, e.g. 'request.submitted'.",
    )
    payload: Payload
