# generated by datamodel-codegen:
#   filename:  request.extracted.schema.json
#   timestamp: 2026-07-17T11:02:36+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .common.envelope_schema import EventEnvelope


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    raw_text: str = Field(
        ...,
        description='Echo of the original patient text, kept alongside the extraction for traceability and for IA3 embedding fallback.',
    )
    symptoms: list[str] = Field(
        ...,
        description="Discrete symptoms/complaints identified in the text, e.g. ['douleur thoracique', 'essoufflement'].",
    )
    severity_keywords: list[str] | None = Field(
        None,
        description="Phrases signalling severity/urgency, used as input signal for IA2, e.g. ['depuis ce matin', 'intense'].",
    )
    duration_hint: str | None = Field(
        None,
        description="How long the patient reports the issue has been present, if stated, e.g. '3 jours'.",
    )
    specialty_hint: str | None = Field(
        None,
        description="Free-text guess at the kind of professional needed, e.g. 'cardiologue'. This is NOT an exact tag — IA3 matches it semantically against professional profiles rather than doing exact string matching.",
    )
    location_hint: str | None = Field(
        None,
        description='Location mentioned in the text, if any, e.g. a neighborhood or city.',
    )
    age_hint: int | None = Field(
        None, description='Patient age if mentioned or inferable from text.', ge=0
    )
    extraction_confidence: float = Field(
        ...,
        description="IA1's confidence in this extraction. Low values may warrant fallback handling downstream.",
        ge=0.0,
        le=1.0,
    )


class RequestExtracted(EventEnvelope):
    """
    Published by IA1 (NLP Triage) after turning the patient's free text into structured data. Consumed by both IA2 (urgency scoring) and IA3 (matching) — so this shape is the shared 'understanding' of the request that the rest of the pipeline builds on.
    """

    event_type: Literal['request.extracted'] = Field(
        ...,
        description="Redis Stream key / logical event name, e.g. 'request.submitted'.",
    )
    payload: Payload
