# generated by datamodel-codegen:
#   filename:  request.refused.schema.json
#   timestamp: 2026-07-17T11:02:36+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .common.envelope_schema import EventEnvelope


class Reason(Enum):
    """
    Why the proposal didn't result in acceptance.
    """

    declined = 'declined'
    timeout = 'timeout'
    unavailable = 'unavailable'
    NoneType_None = None


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pro_id: str = Field(
        ...,
        description='ID of the professional who refused (or failed to respond in time).',
    )
    reason: Reason | None = Field(
        None, description="Why the proposal didn't result in acceptance."
    )
    retry_count: int = Field(
        ...,
        description='How many professionals have already been tried for this request_id, including this refusal.',
        ge=0,
    )


class RequestRefused(EventEnvelope):
    """
    Published by Dispatch Core when the proposed professional refuses or times out (FSM transition: proposed -> refused). Dispatch Core is expected to loop back and try the next candidate, which is why Evaluation tracks refusal rate per strategy as a key KPI.
    """

    event_type: Literal['request.refused'] = Field(
        ...,
        description="Redis Stream key / logical event name, e.g. 'request.submitted'.",
    )
    payload: Payload
