# generated by datamodel-codegen:
#   filename:  request.proposed.schema.json
#   timestamp: 2026-07-17T11:02:36+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from .common.envelope_schema import EventEnvelope


class Strategy(Enum):
    """
    Which matching strategy produced this proposal, so Evaluation can attribute outcomes to a strategy. S1/S2 = classic tag-based matching, S3/S4 = semantic embedding-based matching.
    """

    S1 = 'S1'
    S2 = 'S2'
    S3 = 'S3'
    S4 = 'S4'


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pro_id: str = Field(
        ..., description='ID of the professional being proposed, from Pro Registry.'
    )
    strategy: Strategy = Field(
        ...,
        description='Which matching strategy produced this proposal, so Evaluation can attribute outcomes to a strategy. S1/S2 = classic tag-based matching, S3/S4 = semantic embedding-based matching.',
    )
    match_score: float | None = Field(
        None,
        description='Cosine similarity or ranking score behind this choice, if the strategy produces one (null for purely rule-based strategies).',
    )
    expires_at: AwareDatetime | None = Field(
        None,
        description='Deadline by which the pro must respond before Dispatch Core times the proposal out and tries the next candidate.',
    )


class RequestProposed(EventEnvelope):
    """
    Published by Dispatch Core when it selects and proposes a professional for a request (FSM transition: queued -> proposed). Notification Gateway pushes this to the professional's client.
    """

    event_type: Literal['request.proposed'] = Field(
        ...,
        description="Redis Stream key / logical event name, e.g. 'request.submitted'.",
    )
    payload: Payload
